#Utiliza la imagen oficial de python como base.
FROM python:3.10-slim

#Copia el archivo de python a la imagen.
COPY app_hw.py /home/app_hw.py

#Ejecuta la aplicación cuando se inicia el contenedor.
CMD ["python", "/home/app_hw.py"]
