#Utiliza la imagen oficial de python como base.
FROM python:3.10-slim

#Copia el archivo de python a la imagen.
COPY muestra.py /home/muestra.py

#Ejecuta la aplicación cuando se inicia el contenedor.
CMD ["python", "/home/muestra.py"]
